CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
  	contactNumber VARCHAR(100) UNIQUE,
  	password VARCHAR(150)
  	role VARCHAR(50)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);